"""MCP server for the Acme Corp GTM semantic layer.

Exposes exactly three tools, per build spec Section "Phase 3 -- Semantic /
Context Layer (MCP)":
    list_metrics()
    get_metric_definition(name)
    query_metric(metric, dimensions, filters, grain, date_range)

WHITELIST GUARDRAIL
--------------------
Every tool reads from semantic/metric_registry.json -- the versioned
snapshot generated by semantic/build_registry.py's deterministic parse of
docs/acme-corp-gtm-metric-tree.md. A metric name not in that registry is
rejected, not silently guessed at. A metric IN the registry but with no
`query` mapping (most Layer-2/3 leaves -- see the registry's own
`gap_note` on each) is also rejected by query_metric(), though
get_metric_definition() still returns its tree definition. Every
query_metric() success response echoes the metric's own registry
definition alongside the data, per the same guardrail requirement.

WARM DATA CONNECTION
---------------------
Reads business data from data/acme_gtm.duckdb, read-only, following the
same path/connection pattern as analytics/variance_diagnostic.py
(`os.path.join(os.path.dirname(__file__), "..", "data", "acme_gtm.duckdb")`),
and reads ONLY from the `main_marts` schema's dim_*/fact_*/mart_* tables
-- never stg_/int_/raw -- per analytics-engineering-conventions. A fresh
read-only connection is opened per query_metric() call and closed
immediately after, so this server never holds a lock that would block a
concurrent `dbt build`.

RUN
---
    semantic/.venv/bin/python semantic/server.py

See semantic/README.md for the Python 3.12 venv requirement (the MCP
Python SDK needs >=3.10; this project's default interpreter is 3.9).
"""
import difflib
import json
import os
import re
from datetime import date, datetime
from typing import Any, Dict, List, Optional

import duckdb
from mcp.server.mcpserver import MCPServer

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_HERE)
_REGISTRY_PATH = os.path.join(_HERE, "metric_registry.json")
_DB_PATH = os.path.join(_REPO_ROOT, "data", "acme_gtm.duckdb")

_VALID_SEGMENTS = ("SMB", "Commercial", "Enterprise")
_VALID_GRAINS = ("month", "quarter", "year", "all")
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _load_registry() -> dict:
    if not os.path.exists(_REGISTRY_PATH):
        raise FileNotFoundError(
            f"{_REGISTRY_PATH} does not exist -- run "
            "`semantic/.venv/bin/python semantic/build_registry.py` first."
        )
    with open(_REGISTRY_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


_REGISTRY = _load_registry()
_METRICS: Dict[str, dict] = _REGISTRY["metrics"]
_NAME_INDEX: Dict[str, str] = {n["name"].strip().lower(): key for key, n in _METRICS.items()}


def _registry_stamp() -> dict:
    return {
        "registry_version": _REGISTRY["registry_version"],
        "source_tree_file": _REGISTRY["source_tree_file"],
        "source_tree_sha256": _REGISTRY["source_tree_sha256"],
        "generated_at": _REGISTRY["generated_at"],
    }


def _resolve_metric(name: str) -> Optional[str]:
    """Whitelist lookup: exact key, exact display-name (case-insensitive),
    or a normalized key match ('Win Rate' -> 'win_rate'). Never a fuzzy
    match -- fuzzy suggestions are offered only in the rejection message,
    never silently substituted as the resolved metric."""
    if not name:
        return None
    raw = name.strip()
    if raw in _METRICS:
        return raw
    lowered = raw.lower()
    if lowered in _NAME_INDEX:
        return _NAME_INDEX[lowered]
    normalized = re.sub(r"[^a-z0-9]+", "_", lowered).strip("_")
    if normalized in _METRICS:
        return normalized
    return None


# Common acronyms/spelled-out forms whose characters don't overlap enough
# with their target metric name for difflib's character-level matching to
# find them (e.g. "net revenue retention" shares more characters with
# "logo_retention" than with "nrr") -- checked before the fuzzy fallback so
# the rejection message still points somewhere useful.
_ALIASES = {
    "nrr": "nrr",
    "net revenue retention": "nrr",
    "net_revenue_retention": "nrr",
    "grr": "grr",
    "gross revenue retention": "grr",
    "gross_revenue_retention": "grr",
    "cac": "cac_by_channel",
    "customer acquisition cost": "cac_by_channel",
    "customer_acquisition_cost": "cac_by_channel",
}


def _suggestions(name: str, n: int = 3) -> List[str]:
    alias = _ALIASES.get(name.strip().lower())
    if alias and alias in _METRICS:
        return [alias]
    candidates = list(_METRICS.keys()) + [m["name"] for m in _METRICS.values()]
    return difflib.get_close_matches(name, candidates, n=n, cutoff=0.5)


def _unknown_metric_error(name: str) -> dict:
    return {
        "error": "unknown_metric",
        "message": (
            f"'{name}' is not in the metric registry (whitelist-only per the semantic layer's "
            f"guardrails). Call list_metrics() to see the full registered set."
        ),
        "did_you_mean": _suggestions(name),
        **_registry_stamp(),
    }


def _public_metric(node: dict) -> dict:
    """The fields returned to a caller for a single metric -- the full
    tree definition, minus internal parser bookkeeping (`detail` is kept;
    it's genuine tree sub-bullet text, useful context)."""
    return {
        "key": node["key"],
        "name": node["name"],
        "pillar": node["pillar"],
        "layer": node["layer"],
        "formula": node["formula"],
        "formula_note": node["formula_note"],
        "owner": node["owner"],
        "note": node["note"],
        "scope_note": node["scope_note"],
        "allowed_dimensions": node["allowed_dimensions"],
        "queryable_dimensions": node["queryable_dimensions"],
        "opportunity_type_filter": node["opportunity_type_filter"],
        "source_mart": node["source_mart"],
        "parent": node["parent"],
        "children": node["children"],
        "additive": node["additive"],
        "cross_reference": node["cross_reference"],
        "computable": node["computable"],
        "computability": node["computability"],
        "gap_note": node["gap_note"],
        "detail": node["detail"],
    }


# =====================================================================
# query_metric SQL construction
# =====================================================================

def _grain_expr(grain: str) -> Optional[str]:
    if grain == "all":
        return None
    if grain == "month":
        return "date_trunc('month', month)"
    if grain == "quarter":
        return "date_trunc('quarter', month)"
    if grain == "year":
        return "date_trunc('year', month)"
    raise ValueError(grain)


def _value_expr(query: dict) -> str:
    agg = query["aggregation"]
    if agg == "sum":
        return f"sum({query['column']}) as value"
    if agg == "avg":
        return f"avg({query['column']}) as value"
    if agg == "ratio":
        return f"sum({query['numerator']})::double / nullif(sum({query['denominator']}), 0) as value"
    raise ValueError(f"unsupported aggregation for a plain group-by query: {agg}")


def _validate_date_range(date_range: Optional[dict]) -> tuple:
    if not date_range:
        return None, None
    start, end = date_range.get("start"), date_range.get("end")
    for label, val in (("start", start), ("end", end)):
        if val is not None and not _DATE_RE.match(str(val)):
            raise ValueError(f"date_range.{label} must be 'YYYY-MM-DD', got {val!r}")
    return start, end


def _connect():
    return duckdb.connect(_DB_PATH, read_only=True)


def _run_query_metric(node: dict, dimensions: List[str], filters: Dict[str, str],
                       grain: str, date_range: Optional[dict]) -> dict:
    warnings: List[str] = []
    query = node["query"]

    # --- dimension guardrail: allowed-per-tree vs. queryable-per-data ---
    for d in dimensions:
        if d not in node["allowed_dimensions"]:
            raise _GuardrailError(
                "invalid_dimension",
                f"'{d}' is not an allowed dimension for '{node['key']}'. "
                f"allowed_dimensions per the metric tree: {node['allowed_dimensions']}.",
            )
        if d not in node["queryable_dimensions"]:
            raise _GuardrailError(
                "dimension_not_queryable",
                f"The metric tree allows '{d}' on '{node['key']}', but no mart_* table currently "
                f"exposes that cut -- queryable_dimensions today: {node['queryable_dimensions']}. "
                f"gap_note: {node['gap_note']}",
            )

    # --- filter guardrail ---
    segment_filter = None
    for dim, value in (filters or {}).items():
        if dim not in node["queryable_dimensions"]:
            raise _GuardrailError(
                "invalid_filter_dimension",
                f"Cannot filter '{node['key']}' by '{dim}' -- queryable_dimensions: "
                f"{node['queryable_dimensions']}.",
            )
        if dim == "segment":
            if value not in _VALID_SEGMENTS:
                raise _GuardrailError(
                    "invalid_segment_value",
                    f"'{value}' is not a valid segment -- must be one of {_VALID_SEGMENTS} "
                    f"(never 'tier').",
                )
            segment_filter = value

    if grain not in _VALID_GRAINS:
        raise _GuardrailError("invalid_grain", f"grain must be one of {_VALID_GRAINS}, got {grain!r}")

    start, end = _validate_date_range(date_range)

    if query["aggregation"] == "avg_special":
        return _run_tenure_at_churn(node, dimensions, segment_filter, grain, start, end, warnings)

    select_cols, group_cols, order_cols = [], [], []
    grain_expr = _grain_expr(grain)
    if grain_expr:
        select_cols.append(f"{grain_expr} as period")
        group_cols.append("1")
        order_cols.append("1")
    include_segment = "segment" in dimensions
    if include_segment:
        select_cols.append("segment")
        group_cols.append(str(len(group_cols) + 1) if grain_expr else "1")
        order_cols.append(str(len(order_cols) + 1) if grain_expr else "1")
    select_cols.append(_value_expr(query))

    where_clauses = []
    params: list = []
    if start:
        where_clauses.append("month >= ?")
        params.append(start)
    if end:
        where_clauses.append("month <= ?")
        params.append(end)
    if segment_filter:
        where_clauses.append("segment = ?")
        params.append(segment_filter)

    sql = f"select {', '.join(select_cols)} from main_marts.{node['source_mart']}"
    if where_clauses:
        sql += " where " + " and ".join(where_clauses)
    if group_cols:
        sql += " group by " + ", ".join(group_cols)
    if order_cols:
        sql += " order by " + ", ".join(order_cols)

    con = _connect()
    try:
        cur = con.execute(sql, params)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
    finally:
        con.close()

    data = [_row_to_dict(cols, row) for row in rows]
    if node["computability"] == "partial":
        warnings.append(f"Partially computable: {node['gap_note']}")
    if node["query"]["aggregation"] in ("avg", "sum") and node["gap_note"] and node["computability"] == "full":
        warnings.append(node["gap_note"])
    if not data:
        warnings.append("No rows matched the requested filters/date_range.")

    return {"sql": sql, "data": data, "warnings": warnings}


def _run_tenure_at_churn(node, dimensions, segment_filter, grain, start, end, warnings):
    grain_expr = _grain_expr(grain)
    period_source = "churn_month"
    select_cols, group_cols, order_cols = [], [], []
    if grain_expr:
        period_expr = grain_expr.replace("month", period_source)
        select_cols.append(f"{period_expr} as period")
        group_cols.append("1")
        order_cols.append("1")
    include_segment = "segment" in dimensions
    if include_segment:
        select_cols.append("segment")
        group_cols.append(str(len(group_cols) + 1) if grain_expr else "1")
        order_cols.append(str(len(order_cols) + 1) if grain_expr else "1")
    select_cols.append("avg(account_tenure_days) as value")

    where_clauses = ["month = churn_month", "churn_month is not null"]
    params: list = []
    if start:
        where_clauses.append("churn_month >= ?")
        params.append(start)
    if end:
        where_clauses.append("churn_month <= ?")
        params.append(end)
    if segment_filter:
        where_clauses.append("segment = ?")
        params.append(segment_filter)

    sql = (
        f"select {', '.join(select_cols)} from main_marts.{node['source_mart']} "
        f"where {' and '.join(where_clauses)}"
    )
    if group_cols:
        sql += " group by " + ", ".join(group_cols)
    if order_cols:
        sql += " order by " + ", ".join(order_cols)

    con = _connect()
    try:
        cur = con.execute(sql, params)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
    finally:
        con.close()
    data = [_row_to_dict(cols, row) for row in rows]
    if not data:
        warnings.append("No rows matched the requested filters/date_range.")
    return {"sql": sql, "data": data, "warnings": warnings}


def _row_to_dict(cols: List[str], row: tuple) -> dict:
    out = {}
    for c, v in zip(cols, row):
        if isinstance(v, (datetime, date)):
            out[c] = v.isoformat()
        else:
            out[c] = v
    return out


class _GuardrailError(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


# =====================================================================
# MCP server + tools
# =====================================================================

mcp = MCPServer(
    name="acme-gtm-semantic-layer",
    instructions=(
        "Acme Corp GTM metric tree, exposed as a whitelisted, queryable semantic layer. "
        "Use list_metrics() to browse the registry, get_metric_definition(name) to read a "
        "metric's formula/owner/lineage, and query_metric(...) to pull real data from the dbt "
        "marts. Only metrics returned by list_metrics() can be queried or defined -- anything "
        "else is rejected. Segment values are SMB / Commercial / Enterprise only (never 'tier')."
    ),
)


@mcp.tool()
def list_metrics(pillar: Optional[str] = None, layer: Optional[int] = None,
                  computable_only: bool = False) -> Dict[str, Any]:
    """List every metric in the registry (optionally filtered by pillar
    Growth/Efficiency/Durability, by layer 1/2/3, or restricted to metrics
    query_metric() can actually execute). This IS the whitelist -- any
    metric name not returned here will be rejected by the other two
    tools."""
    out = []
    for key in _REGISTRY["metric_order"]:
        node = _METRICS[key]
        if pillar and node["pillar"].lower() != pillar.lower():
            continue
        if layer and node["layer"] != layer:
            continue
        if computable_only and not node["computable"]:
            continue
        out.append({
            "key": node["key"],
            "name": node["name"],
            "pillar": node["pillar"],
            "layer": node["layer"],
            "parent": node["parent"],
            "additive": node["additive"],
            "computable": node["computable"],
        })
    return {
        "metrics": out,
        "count": len(out),
        "pillars": _REGISTRY["pillars"],
        **_registry_stamp(),
    }


@mcp.tool()
def get_metric_definition(name: str) -> Dict[str, Any]:
    """Full tree definition for one metric: formula, owner, allowed
    dimensions, source mart, parent/children lineage, additivity, and (if
    the metric isn't directly queryable) why not. `name` may be the
    registry key ('win_rate') or the tree's display name ('Win rate')."""
    key = _resolve_metric(name)
    if key is None:
        return _unknown_metric_error(name)
    return {"metric": _public_metric(_METRICS[key]), **_registry_stamp()}


@mcp.tool()
def query_metric(metric: str, dimensions: Optional[List[str]] = None,
                  filters: Optional[Dict[str, str]] = None, grain: str = "month",
                  date_range: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
    """Query real data for one whitelisted metric from the finished dbt
    marts (main_marts schema -- dim_*/fact_*/mart_* only, never
    stg_/int_/raw). Every response (success or rejection) echoes the
    metric's own tree definition alongside the result, per the semantic
    layer's guardrail requirement.

    metric: registry key or tree display name (whitelist-only).
    dimensions: subset of the metric's allowed_dimensions to group by
        (currently only 'segment' is backed by real mart columns; 'channel'
        / 'opportunity_type' are listed on some metrics per the tree but
        rejected today as a documented data gap -- see queryable_dimensions
        on the metric's own definition).
    filters: e.g. {"segment": "Enterprise"}.
    grain: 'month' (default) | 'quarter' | 'year' | 'all'.
    date_range: {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"}, either end
        optional; omit entirely for the full 2020-01 - 2025-12 history.
    """
    dimensions = dimensions or []
    filters = filters or {}

    key = _resolve_metric(metric)
    if key is None:
        return _unknown_metric_error(metric)
    node = _METRICS[key]
    public = _public_metric(node)

    if not node["additive"]:
        return {
            "error": "non_additive_metric",
            "message": (
                f"'{node['name']}' is an explicitly non-additive node per the metric tree "
                f"(note: {node['note']!r}) -- it is never summed into its parent's calculation and "
                f"is not queryable as a rollup contributor. " +
                (f"It also has no computable mart data: {node['gap_note']}" if not node["computable"] else "")
            ),
            "metric": public,
            **_registry_stamp(),
        }

    if not node["computable"]:
        suggestion = node["parent"] if node["parent"] and _METRICS.get(node["parent"], {}).get("computable") else None
        return {
            "error": "metric_not_queryable",
            "message": f"'{node['name']}' is registered but has no queryable mart mapping. {node['gap_note']}",
            "suggested_alternative": suggestion,
            "metric": public,
            **_registry_stamp(),
        }

    try:
        result = _run_query_metric(node, dimensions, filters, grain, date_range)
    except _GuardrailError as e:
        return {"error": e.code, "message": e.message, "metric": public, **_registry_stamp()}
    except ValueError as e:
        return {"error": "invalid_request", "message": str(e), "metric": public, **_registry_stamp()}

    return {
        "metric": public,
        "query": {
            "metric": key, "dimensions": dimensions, "filters": filters,
            "grain": grain, "date_range": date_range,
        },
        "sql": result["sql"],
        "data": result["data"],
        "warnings": result["warnings"],
        **_registry_stamp(),
    }


if __name__ == "__main__":
    mcp.run()
