"""fact_sales_activities generator.

Build spec Section 5 ("Sales engagement"): `outbound_activities` (Enterprise
only), `meetings_booked`, `fact_sales_activities` (rep, opportunity,
activity_type, outcome, timestamp, `competitive_signal` flag --
"individual-activity grain, not pre-aggregated; this is what makes 'are
meetings correlated with wins' answerable at all"). This module is the whole
of that bullet: one raw table, event grain, one row per rep-opportunity
touch.

Scope: Commercial and Enterprise new-business opportunities only.
--------------------------------------------------------------------------
SMB has no rep (build spec Section 1, "Fully automated -- no rep") and gets
no rows. Expansion and renewal opportunities are AM-owned, and AM engagement
already has its own event-grain table (am_activity.py's touchpoints/QBRs/
check-ins) -- covering that population again here would duplicate an
existing grain rather than fill the real gap the build spec names. New-
business is also exactly the population Wave 4's "deal-level diagnostics"
(win/loss) and "rep productivity & coaching diagnostics" (ISR/AE coaching,
not AM) read.

Design decisions (build spec text underdetermines both)
--------------------------------------------------------
* **`outbound_activities` (Enterprise only)** is implemented as a boolean
  column, `is_outbound_touch`, not a second activity_type value. Every row
  in this table already carries an opportunity_id, so "outbound" here means
  a rep-initiated prospecting touch into an already-open Enterprise deal's
  buying committee (multi-threading), not the acquisition-channel sense of
  "outbound SDR" the metric tree already tracks under win rate at the
  account-channel level -- that volume predates any opportunity and belongs
  to a different table this batch does not produce. Outbound-ness is a mode
  a call or email is worked in, not a distinct kind of thing that happened,
  so it is orthogonal to activity_type rather than a value of it. Scoped to
  Enterprise call/email touches only (config.SALES_ACTIVITY_OUTBOUND_SHARE_
  ENTERPRISE); Commercial's pooled-book ISR motion is reactive follow-
  through and carries none; meetings/demos are scheduled events, not
  prospecting touches, so neither carries the flag either.
* **`meetings_booked`** is represented as a `meeting`-type outcome inside
  this one table, not a second table. A meeting is generated as *two* rows
  sharing one participant slot: a `booked` row at the scheduling timestamp,
  and a resolution row (`held` / `no_show` / `rescheduled` / `cancelled`)
  at the meeting date -- config.SALES_ACTIVITY_MEETING_LEAD_DAYS_RANGE
  later, clipped to the opportunity's close_date. This keeps "booked-but-
  not-yet-held vs. held" a real, event-grain distinction (two dated rows)
  rather than a single mutable status field, without inventing a table the
  build spec's own "rather than a second table" framing (see this batch's
  orchestrating prompt) doesn't ask for.

Causal wiring
-------------
Every driver below is a real function of deal/rep characteristics already
generated by opportunities.py, reps.py and rep_status_history.csv -- never
an independent draw (CLAUDE.md's "independently-random columns are a bug"
invariant):

* **Cadence, not a separate volume knob.** Touches are placed by sampling
  successive gaps (config.SALES_ACTIVITY_BASE_GAP_DAYS, exponential) inside
  [created_date, close_date] until the window fills. A tighter mean gap
  simply fits more touches into the same window, so volume and cadence are
  one mechanism, not two independently-tuned ones -- and the realized
  inter-touch gap is a genuine, measurable "response latency" signal.
* **is_won** tightens cadence and lifts meeting/demo held-rate and call-
  connect/email-reply rates: a deal that closed was worked harder and
  engaged better than one that didn't. This reads the opportunity's already-
  fixed outcome the same way opportunities.py itself reads is_won/loss_
  reason to set POC outcome and forecast_category -- a historical log
  generated after the fact, not a live point-in-time judgement (unlike
  fact_forecast_submissions, which is expressly forbidden from doing this).
* **Rep ramp status** (same 180-day hire_date cutoff opportunities.py uses)
  loosens cadence and lowers held/connect/reply rates and multi-threading
  breadth for a ramping rep relative to a ramped one -- QA plan Test C's
  ramp-status requirement, applied to engagement quality, not just win
  assignment.
* **Multi-threading** (distinct `contact_ref` touched per opportunity) is a
  function of is_won and ramp status: winning, ramped-rep deals spread
  across more of the segment's buying-committee pool; losing, ramping-rep
  deals concentrate on one or two contacts.
* **competitive_signal** is elevated, not saturated, on deals whose
  eventual `loss_reason == 'competitive'`, present at a low baseline
  everywhere else (config.SALES_ACTIVITY_COMPETITIVE_SIGNAL_RATE) -- so it
  correlates with the loss reason without becoming a perfect predictor.

Injected incidents (QA plan grounding requirement 3)
-----------------------------------------------------
* **#3, meetings-rise-without-SQO-rise decoupling**: opportunities *created*
  inside config.SALES_ACTIVITY_DECOUPLING_INCIDENT_WINDOW get a uniformly
  tightened cadence (more activity, including more meetings) regardless of
  eventual outcome -- win rate and SQO-stage conversion for that cohort are
  untouched, since opportunities.csv is read here and never rewritten.
* **#4, underperforming rep cohort**: a fixed share of ISR/AE reps
  (config.SALES_ACTIVITY_UNDERPERFORMER_SHARE) carry a persistent, ramp-
  independent quality penalty on cadence, held-rate and multi-threading --
  visible only in this activity data, not in opportunities.csv, since that
  table's win/loss outcomes are already fixed and this batch cannot
  retroactively move them.

`contact_ref` is a synthetic per-opportunity participant slot
(f"{opportunity_id}-C{n}"), not a real contact identity -- this project has
no `contacts` table yet (build spec Section 5 lists one; no generator has
produced it). It exists solely to make multi-threading breadth a countable,
real quantity (distinct `contact_ref` per opportunity) rather than
decoration.
"""
import numpy as np
import pandas as pd

from . import config

_RAMP_FULL_DAYS = 180  # matches opportunities.py's _RAMP_FULL_DAYS


def _departed_by(rep_status_history: pd.DataFrame) -> dict:
    departed = rep_status_history[rep_status_history["status"] == "departed"]
    return dict(zip(departed["rep_id"], pd.to_datetime(departed["effective_date"])))


def _eligible_reps(users: pd.DataFrame, departed_by: dict, rep_type: str, at_date) -> pd.DataFrame:
    at_ts = pd.Timestamp(at_date)
    pool = users[users["rep_type"] == rep_type]
    hired = pd.to_datetime(pool["hire_date"]) <= at_ts
    not_departed = ~pool["rep_id"].map(lambda r: r in departed_by and departed_by[r] <= at_ts)
    return pool[hired & not_departed]


def _is_ramped(hire_date, at_date) -> bool:
    return (pd.Timestamp(at_date) - pd.Timestamp(hire_date)).days >= _RAMP_FULL_DAYS


def _assign_underperformer_cohort(rng: np.random.Generator, users: pd.DataFrame) -> set:
    """Injected incident #4: a fixed, persistent subset of ISR/AE reps
    (never SE -- SE only ever appears here as a supporting demo-giver, not
    a deal owner). SMB has no rep and AM isn't scoped into this table, so
    only ISR/AE are eligible for the cohort at all."""
    pool = users[users["rep_type"].isin(["ISR", "AE"])]
    is_under = rng.random(len(pool)) < config.SALES_ACTIVITY_UNDERPERFORMER_SHARE
    return set(pool.loc[is_under, "rep_id"])


def _mean_gap_days(segment: str, is_won: bool, rep_is_ramped: bool, rep_is_underperformer: bool,
                    in_decoupling_window: bool) -> float:
    gap = config.SALES_ACTIVITY_BASE_GAP_DAYS[segment]
    if is_won:
        gap *= config.SALES_ACTIVITY_GAP_WON_MULTIPLIER
    if not rep_is_ramped:
        gap *= config.SALES_ACTIVITY_GAP_RAMPING_MULTIPLIER
    if rep_is_underperformer:
        gap *= config.SALES_ACTIVITY_GAP_UNDERPERFORMER_MULTIPLIER
    if in_decoupling_window:
        gap *= config.SALES_ACTIVITY_DECOUPLING_GAP_MULTIPLIER
    return max(gap, 0.4)


def _touch_timestamps(rng: np.random.Generator, created_date, close_date, mean_gap: float) -> list:
    """Sequential-gap cadence fill: keep adding exponential(mean_gap) gaps
    until the [created_date, close_date] window is exhausted. Volume and
    latency fall out of this one mechanism -- a tighter mean_gap both fits
    more touches into the window and IS the measurable response-latency
    signal, rather than two knobs that could disagree with each other.
    Guarantees at least one touch."""
    start = pd.Timestamp(created_date)
    end = pd.Timestamp(close_date)
    span_days = max((end - start).days, 0)

    timestamps = []
    cursor = 0.0
    # Hard cap so a pathological (near-zero) mean_gap can't spin forever;
    # segment/window combinations in practice land far under this.
    for _ in range(500):
        cursor += float(rng.exponential(mean_gap))
        if cursor > span_days:
            break
        timestamps.append(start + pd.Timedelta(days=cursor))
    if not timestamps:
        timestamps = [start + pd.Timedelta(days=span_days / 2.0)]
    return timestamps


def _new_contact_probability(is_won: bool, rep_is_ramped: bool, rep_is_underperformer: bool) -> float:
    prob = config.SALES_ACTIVITY_THREADING_BASE_FRACTION
    if is_won:
        prob += config.SALES_ACTIVITY_THREADING_WON_BOOST
    if not rep_is_ramped:
        prob -= config.SALES_ACTIVITY_THREADING_RAMPING_PENALTY
    if rep_is_underperformer:
        prob -= config.SALES_ACTIVITY_THREADING_UNDERPERFORMER_PENALTY
    return float(np.clip(prob, 0.05, 1.0))


def _next_contact_ref(rng: np.random.Generator, opportunity_id: str, touched_slots: list,
                       pool_size: int, new_contact_probability: float) -> str:
    """Each touch either opens a new buying-committee contact (up to
    pool_size) or reinforces one already touched -- decided per touch, so
    expected distinct-contact count scales smoothly with the causal drivers
    even against a small pool (Commercial), rather than collapsing under
    integer rounding the way a single pool-fraction-per-opportunity draw
    would."""
    if len(touched_slots) < pool_size and (not touched_slots or rng.random() < new_contact_probability):
        idx = len(touched_slots)
        touched_slots.append(idx)
    else:
        idx = touched_slots[int(rng.integers(0, len(touched_slots)))]
    return f"{opportunity_id}-C{idx}"


def _held_rate(is_won: bool, rep_is_ramped: bool, rep_is_underperformer: bool) -> float:
    rate = config.SALES_ACTIVITY_HELD_RATE_BASE
    if is_won:
        rate += config.SALES_ACTIVITY_HELD_RATE_WON_BOOST
    if not rep_is_ramped:
        rate -= config.SALES_ACTIVITY_HELD_RATE_RAMPING_PENALTY
    if rep_is_underperformer:
        rate -= config.SALES_ACTIVITY_HELD_RATE_UNDERPERFORMER_PENALTY
    return float(np.clip(rate, 0.05, 0.95))


def _connect_rate(is_won: bool, rep_is_ramped: bool, rep_is_underperformer: bool) -> float:
    rate = config.SALES_ACTIVITY_CONNECT_RATE_BASE
    if is_won:
        rate += config.SALES_ACTIVITY_CONNECT_RATE_WON_BOOST
    if not rep_is_ramped:
        rate -= config.SALES_ACTIVITY_CONNECT_RATE_RAMPING_PENALTY
    if rep_is_underperformer:
        rate -= config.SALES_ACTIVITY_CONNECT_RATE_UNDERPERFORMER_PENALTY
    return float(np.clip(rate, 0.05, 0.95))


def _reply_rate(is_won: bool, rep_is_ramped: bool, rep_is_underperformer: bool) -> float:
    rate = config.SALES_ACTIVITY_REPLY_RATE_BASE
    if is_won:
        rate += config.SALES_ACTIVITY_REPLY_RATE_WON_BOOST
    if not rep_is_ramped:
        rate -= config.SALES_ACTIVITY_REPLY_RATE_RAMPING_PENALTY
    if rep_is_underperformer:
        rate -= config.SALES_ACTIVITY_REPLY_RATE_UNDERPERFORMER_PENALTY
    return float(np.clip(rate, 0.05, 0.95))


def _competitive_signal_rate(is_won: bool, loss_reason) -> float:
    if is_won:
        return config.SALES_ACTIVITY_COMPETITIVE_SIGNAL_RATE["won"]
    if loss_reason == "competitive":
        return config.SALES_ACTIVITY_COMPETITIVE_SIGNAL_RATE["competitive_loss"]
    return config.SALES_ACTIVITY_COMPETITIVE_SIGNAL_RATE["other_loss"]


def _call_outcome(rng: np.random.Generator, connect_rate: float) -> str:
    remaining = 1.0 - connect_rate
    # Fixed relative shares among the non-connect outcomes -- own resolved
    # decision, held constant while connect_rate itself moves with the
    # causal drivers above.
    voicemail, no_answer, gatekeeper = remaining * 0.45, remaining * 0.40, remaining * 0.15
    return str(rng.choice(
        ["connected", "voicemail", "no_answer", "gatekeeper"],
        p=[connect_rate, voicemail, no_answer, gatekeeper],
    ))


def _email_outcome(rng: np.random.Generator, reply_rate: float) -> str:
    remaining = 1.0 - reply_rate
    opened, no_response, bounced = remaining * 0.45, remaining * 0.48, remaining * 0.07
    return str(rng.choice(
        ["replied", "opened_no_reply", "no_response", "bounced"],
        p=[reply_rate, opened, no_response, bounced],
    ))


def _meeting_resolution(rng: np.random.Generator, held_rate: float) -> str:
    remaining = 1.0 - held_rate
    no_show, rescheduled, cancelled = remaining * 0.45, remaining * 0.35, remaining * 0.20
    return str(rng.choice(
        ["held", "no_show", "rescheduled", "cancelled"],
        p=[held_rate, no_show, rescheduled, cancelled],
    ))


def _demo_outcome(rng: np.random.Generator, held_rate: float) -> str:
    remaining = 1.0 - held_rate
    return str(rng.choice(["held", "no_show", "cancelled"], p=[held_rate, remaining * 0.6, remaining * 0.4]))


def generate_sales_activities(rng: np.random.Generator, opportunities: pd.DataFrame,
                               users: pd.DataFrame, rep_status_history: pd.DataFrame) -> pd.DataFrame:
    departed_by = _departed_by(rep_status_history)
    hire_date_by_rep = dict(zip(users["rep_id"], pd.to_datetime(users["hire_date"])))
    underperformers = _assign_underperformer_cohort(rng, users)

    decoupling_start, decoupling_end = (pd.Timestamp(d) for d in config.SALES_ACTIVITY_DECOUPLING_INCIDENT_WINDOW)
    lead_lo, lead_hi = config.SALES_ACTIVITY_MEETING_LEAD_DAYS_RANGE

    new_business = opportunities[
        (opportunities["opportunity_type"] == "new_business")
        & (opportunities["segment"].isin(["Commercial", "Enterprise"]))
    ]

    rows = []
    seq = 0

    for opp in new_business.itertuples():
        segment = opp.segment
        rep_id = opp.rep_id
        if rep_id not in hire_date_by_rep:
            continue  # defensive; every new-business opp carries a real rep_id in this project's data
        created_ts = pd.Timestamp(opp.created_date)
        close_ts = pd.Timestamp(opp.close_date)
        if close_ts < created_ts:
            continue

        rep_is_ramped = _is_ramped(hire_date_by_rep[rep_id], opp.created_date)
        rep_is_underperformer = rep_id in underperformers
        in_decoupling_window = decoupling_start <= created_ts <= decoupling_end

        mean_gap = _mean_gap_days(segment, opp.is_won, rep_is_ramped, rep_is_underperformer, in_decoupling_window)
        touch_slots = _touch_timestamps(rng, opp.created_date, opp.close_date, mean_gap)

        pool_size = config.SALES_ACTIVITY_CONTACT_POOL_SIZE[segment]
        new_contact_probability = _new_contact_probability(opp.is_won, rep_is_ramped, rep_is_underperformer)
        touched_slots: list = []
        held_rate = _held_rate(opp.is_won, rep_is_ramped, rep_is_underperformer)
        connect_rate = _connect_rate(opp.is_won, rep_is_ramped, rep_is_underperformer)
        reply_rate = _reply_rate(opp.is_won, rep_is_ramped, rep_is_underperformer)
        comp_signal_rate = _competitive_signal_rate(opp.is_won, opp.loss_reason)

        type_mix = config.SALES_ACTIVITY_TYPE_MIX[segment]
        type_names = list(type_mix.keys())
        type_probs = list(type_mix.values())

        # Eligible SE pool for Enterprise demos, evaluated once per
        # opportunity at created_date -- a light touch of realism (an SE
        # hired mid-deal wouldn't have been assignable at deal open); not
        # re-evaluated per touch since SE staffing on a deal doesn't churn
        # touch-by-touch the way rep ramp status does.
        se_pool = (
            _eligible_reps(users, departed_by, "SE", opp.created_date)
            if segment == "Enterprise" else pd.DataFrame(columns=users.columns)
        )

        for slot_ts in touch_slots:
            activity_type = str(rng.choice(type_names, p=type_probs))
            contact_ref = _next_contact_ref(rng, opp.opportunity_id, touched_slots, pool_size, new_contact_probability)
            comp_signal = bool(rng.random() < comp_signal_rate)

            if activity_type == "meeting":
                seq += 1
                rows.append({
                    "activity_id": f"SAC-{seq:08d}", "rep_id": rep_id, "opportunity_id": opp.opportunity_id,
                    "activity_type": "meeting", "outcome": "booked", "activity_timestamp": slot_ts,
                    "contact_ref": contact_ref, "competitive_signal": comp_signal, "is_outbound_touch": False,
                })
                lead_days = int(rng.integers(lead_lo, lead_hi + 1))
                resolve_ts = min(slot_ts + pd.Timedelta(days=lead_days), close_ts)
                if resolve_ts <= slot_ts:
                    resolve_ts = slot_ts + pd.Timedelta(hours=4)
                seq += 1
                rows.append({
                    "activity_id": f"SAC-{seq:08d}", "rep_id": rep_id, "opportunity_id": opp.opportunity_id,
                    "activity_type": "meeting", "outcome": _meeting_resolution(rng, held_rate),
                    "activity_timestamp": resolve_ts, "contact_ref": contact_ref,
                    "competitive_signal": bool(rng.random() < comp_signal_rate), "is_outbound_touch": False,
                })
                continue

            if activity_type == "demo":
                demo_rep_id = rep_id
                if segment == "Enterprise" and len(se_pool) and rng.random() < config.SALES_ACTIVITY_SE_SHARE_OF_DEMO:
                    demo_rep_id = str(se_pool.iloc[int(rng.integers(0, len(se_pool)))]["rep_id"])
                seq += 1
                rows.append({
                    "activity_id": f"SAC-{seq:08d}", "rep_id": demo_rep_id, "opportunity_id": opp.opportunity_id,
                    "activity_type": "demo", "outcome": _demo_outcome(rng, held_rate),
                    "activity_timestamp": slot_ts, "contact_ref": contact_ref,
                    "competitive_signal": comp_signal, "is_outbound_touch": False,
                })
                continue

            is_outbound = bool(
                segment == "Enterprise"
                and activity_type in ("call", "email")
                and rng.random() < config.SALES_ACTIVITY_OUTBOUND_SHARE_ENTERPRISE
            )
            outcome = _call_outcome(rng, connect_rate) if activity_type == "call" else _email_outcome(rng, reply_rate)
            seq += 1
            rows.append({
                "activity_id": f"SAC-{seq:08d}", "rep_id": rep_id, "opportunity_id": opp.opportunity_id,
                "activity_type": activity_type, "outcome": outcome, "activity_timestamp": slot_ts,
                "contact_ref": contact_ref, "competitive_signal": comp_signal, "is_outbound_touch": is_outbound,
            })

    df = pd.DataFrame(rows)
    df = df.sort_values(["activity_timestamp", "activity_id"]).reset_index(drop=True)
    return df


ACTIVITY_COLUMNS = [
    "activity_id", "rep_id", "opportunity_id", "activity_type", "outcome",
    "activity_timestamp", "contact_ref", "competitive_signal", "is_outbound_touch",
]
